name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Frontend install
        working-directory: frontend
        run: npm install

      - name: Frontend tests (Jest)
        working-directory: frontend
        run: npm test -- --watchAll=false

      - name: Frontend build
        working-directory: frontend
        run: npm run build

      - name: Backend install
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Backend build check
        run: python -m compileall backend/app

    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-tracker-dashboard:latest
